services:
  db:
    image: mysql:8.0
    container_name: sphere_db
    environment:
      MYSQL_DATABASE: 7G10
      MYSQL_ROOT_PASSWORD: rootlocalpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080 # Accede por http://localhost:8081

  web:
    build:
      context: .
      dockerfile: inline.Dockerfile
    container_name: sphere_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db